export enum PAGES {
  // MAIN
  LOGIN = "login",
  REGISTER = "register",
  PO_REQUESTS = "po_requests",
  PC_REQUESTS = "pc_requests",
  SITE_REQUESTS = "site_requests",
  MATERIAL_REQUESTS = "material_requests",
  EMPLOYEE_REQUESTS = "employee_requests",
  DCC = "dcc",
  CHAT = "chat",
  TASKS = "tasks",
  TASK = "task",
  Task_INFO = "task_rev",
  PROFILE = "profile",
  PERSONAL_PROFILE = "personal_profile",
  TENDERS = "tenders",
  SETTINGS = "settings",
  INVOICES = "invoices",
  PROJECTS = "projects",
  MANAGERS = "managers",
  EMPLOYEES = "employees",
  CUSTOMERS = "customers",
  SUBCONTRACTORS = "subcontractors",
  CONTRACTS = "contracts",
  SUPPLIERS = "suppliers",
  ATTENDANCE = "attendance",
  INVENTORIES = "inventories",
  COST_CENTER = "cost_center",
  DAILY_REPORTS = "daily_reports",
  PROCUREMENT_PLAN = "procurement_plan",
  CONSTRUCTION_PLAN = "construction_plan",
  TODO = "todos",

  // Details
  PO_REQUEST_INFO = "po_request_rev",
  PC_REQUEST_INFO = "pc_request_rev",
  SITE_REQUEST_INFO = "site_request_rev",
  MATERIAL_REQUEST_INFO = "material_request_rev",
  EMPLOYEE_REQUEST_INFO = "employee_request_rev",
  INVOICE_INFO = "invoice_rev",
  CONTRACT_INFO = "contract_rev",
  CUSTOMER_INFO = "customer_rev",
  SUBCONTRACTOR_INFO = "subcontractor_rev",
  SUPPLIER_INFO = "supplier_rev",
  EMPLOYEE_INFO = "employee_rev",
  PROJECT_INFO = "project_rev",
  TENDER_INFO = "tender_rev",
  DAILY_REPORT_INFO = "daily_report_rev",

  // Create or Edit
  PO_REQUEST = "po_request",
  PC_REQUEST = "pc_request",
  SITE_REQUEST = "site_request",
  MATERIAL_REQUEST = "material_request",
  EMPLOYEE_REQUEST = "employee_request",
  INVOICE = "invoice",
  CONTRACT = "contract",
  CUSTOMER = "customer",
  SUBCONTRACTOR = "subcontractor",
  SUPPLIER = "supplier",
  EMPLOYEE = "employee",
  PROJECT = "project",
  TENDER = "tender",
  DAILY_REPORT = "daily_report",

  INVENTORY = "inventory",

  INVENTORY_ITEM = "inventory_item",
  MATERIAL_FORWARDING_REQUEST = "material_forward",

  HR = "hr",
  IT = "it",
  MARKETING = "marketing",
  PROCUREMENT = "procurement",
  CONSTRUCTION = "construction",
  FINANCE = "finance",

  REPORTS = "reports",
  GROUPS = "groups",

  // -----

  // -----
  // -----
  // JOB_OFFER = "job_offer",
  PROJECT_INV = "project_inv",
  Enquires = "Enquires",
  Enquires_DETAILS = "Enquires-detail",
  NOTIFICATIONS = "notifications",
  COMPANY = "company",
  // STEPPER = "stepper",
  // STEP_TWO = "step_two",
  CUSTOMER_SUPPLIER = "customer-supplier",
  SALARIES = "salaries",
  // --------------

  // --------------
  PASSWORD_RESET = "password-reset",
  NEW_PASSWORD = "new-password",
  VERIFY_EMAIL = "verify-email",
  // SUMMARY = "summary",
  // CALENDAR = "calendar",
  // CATEGORIES = "departments"
}
