export const SideBarMenuData: any[] = [
  // ******************************** With Children Menus
  //  Dashboard - KPI
  {
    name: "Dashboard - KPI",
    routerLink: ["/"],
    identifier: "dashboard-KPI",
    iconClass: "icofont-dashboard-web",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "HR", "Finance", "Marketing", "Tender", "Procurement"],
  },
  //Profile
  {
    name: "Profile",
    routerLink: ["/"],
    identifier: "Profile",
    iconClass: "icofont-ui-user",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "HR", "Finance", "Marketing", "Tender", "Procurement"],
  },
  // Requests
  {
    name: "Requests",
    routerLink: ["/"],
    identifier: "PO_requests",
    // iconClass: "icofont-users-alt-1",
    iconClass: "icofont-paper",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [
      {
        name: "Employee Requests",
        routerLink: ["/employee_requests"],
        identifier: "Employee_requests",
        iconClass: "icofont-users-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Procurement", "Tender", "Finance", "HR"],
      },
      {
        name: "PO Requests",
        routerLink: ["/po_requests"],
        identifier: "PO_requests",
        iconClass: "icofont-users-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Procurement", "Tender", "Finance"],
      },
      {
        name: "PC Requests",
        routerLink: ["/pc_requests"],
        identifier: "pc_requests",
        iconClass: "icofont-file-spreadsheet",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Procurement", "Tender", "Finance"],
      },
      {
        name: "Site Requests",
        routerLink: ["/site_requests"],
        identifier: "Site_Requests",
        iconClass: "icofont-file-spreadsheet",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Procurement", "Tender", "Finance"],
      },
      {
        name: "Material Requests",
        routerLink: ["/material_requests"],
        identifier: "Material_Requests",
        iconClass: "icofont-file-spreadsheet",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Procurement", "Tender", "Finance"],
      },
      {
        name: "Contracts",
        routerLink: ["/contracts"],
        identifier: "Contracts",
        iconClass: "icofont-briefcase",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: false,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Procurement", "Tender", "Finance"],
      },
    ],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "Finance", "Procurement", "Tender", "HR"],
  },
  // Projects
  {
    name: "Projects",
    routerLink: ["/"],
    identifier: "Projects",
    iconClass: "icofont-briefcase",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [
      {
        name: "Suppliers",
        routerLink: ["/suppliers"],
        identifier: "Suppliers",
        iconClass: "icofont-business-man-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Finance", "HR", "Procurement", "Tender"],
      },
      {
        name: "Customers",
        routerLink: ["/customers"],
        identifier: "Customers",
        iconClass: "icofont-business-man-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Finance", "HR", "Procurement", "Tender"],
      },
      {
        name: "Subcontractors",
        routerLink: ["/subcontractors"],
        identifier: "Subcontractors",
        iconClass: "icofont-business-man-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
        departments: ["Projects", "Finance", "HR", "Procurement", "Tender"],
      },
    ],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "Procurement", "Tender", "HR"],
  },
  {
    name: "Attendance",
    routerLink: ["/"],
    identifier: "Attendance",
    iconClass: "icofont-users-alt-1",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "HR", "Finance", "Marketing", "Tender", "Procurement"],
  },
  //Task
  {
    name: "Tasks",
    routerLink: ["/tasks"],
    identifier: "Tasks",
    iconClass: "icofont-tasks-alt",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "HR", "Finance", "Marketing", "Tender", "Procurement"],
  },

  // HR Only
  {
    name: "HR Sec",
    routerLink: ["/"],
    identifier: "HR Sec",
    iconClass: "icofont-users-alt-1",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [
      {
        name: "Managers",
        routerLink: ["/managers"],
        identifier: "Managers",
        iconClass: "icofont-users-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "Director", "Manager", "User"],
      },
      {
        name: "Employees",
        routerLink: ["/employees"],
        identifier: "Employees",
        iconClass: "icofont-users-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "Director", "Manager", "User"],
      },
      {
        name: "Attendance",
        routerLink: ["/attendance"],
        identifier: "Attendance",
        iconClass: "icofont-file-spreadsheet",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "Director", "Manager", "User"],
      },
      {
        name: "Salaries",
        routerLink: ["/salaries"],
        identifier: "Salaries",
        iconClass: "icofont-file-spreadsheet",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
      },
      {
        name: "Job Offer",
        routerLink: ["/job_offer"],
        identifier: "Job Offer",
        iconClass: "icofont-file-spreadsheet",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "User", "Manager", "Director"],
      },
    ],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["HR"],
  },
  // HR for all
  {
    name: "HR Sec",
    routerLink: ["/"],
    identifier: "HR Sec",
    iconClass: "icofont-users-alt-1",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [
      {
        name: "Managers",
        routerLink: ["/managers"],
        identifier: "Managers",
        iconClass: "icofont-users-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "Director", "Manager"],
      },
      {
        name: "Employees",
        routerLink: ["/employees"],
        identifier: "Employees",
        iconClass: "icofont-users-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "Director", "Manager"],
      },
      {
        name: "Customers",
        routerLink: ["/customers"],
        identifier: "Customers",
        iconClass: "icofont-business-man-alt-1",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "Director", "Manager"],
      },
      {
        name: "Attendance",
        routerLink: ["/attendance"],
        identifier: "Attendance",
        iconClass: "icofont-file-spreadsheet",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "Director", "Manager"],
      },
      {
        name: "Salaries",
        routerLink: ["/salaries"],
        identifier: "Salaries",
        iconClass: "icofont-file-spreadsheet",
        breadcrumbMessage: "",
        isCategory: false,
        isApp: true,
        children: [],
        roles: ["Superuser", "Director", "Manager"],
      },
    ],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "Procurement", "Tender"],
  },

  // ******************************** Without Children Menus
  // Procurement Plan
  {
    name: "Procurement Plan",
    routerLink: ["/procurement_plan"],
    identifier: "Procurement Plan",
    iconClass: "icofont-briefcase",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
    roles: ["Superuser", "Manager", "Director"],
    departments: ["Projects", "Procurement", "Tender"],
  },
  // Construction Plan
  {
    name: "Construction Plan",
    routerLink: ["/construction_plan"],
    identifier: "Construction Plan",
    iconClass: "icofont-briefcase",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
    roles: ["Superuser", "Manager", "Director"],
    departments: ["Projects", "Procurement", "Tender"],
  },
  // Inventory
  {
    name: "Inventory",
    routerLink: ["/inventory"],
    identifier: "Inventory",
    iconClass: "icofont-briefcase",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "Procurement", "Tender"],
  },

  // *************************************************************
  // <Tender Department>
  {
    name: "Tenders",
    routerLink: ["/tenders"],
    identifier: "Tenders",
    iconClass: "icofont-file-spreadsheet",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Tender", "HR"],
  },
  // <Marketing Department>
  {
    name: "Marketing",
    routerLink: ["/marketing"],
    identifier: "Marketing",
    iconClass: "icofont-unique-idea",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Marketing"],
  },

  // *************************************************************
  // <Open For All Departments>
  {
    name: "DCC",
    routerLink: ["/dcc"],
    identifier: "DCC",
    iconClass: "icofont-briefcase",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "HR", "Finance", "Marketing", "Tender", "Procurement"],
  },
  // {
  //   name: "Groups",
  //   routerLink: ["/groups"],
  //   identifier: "Groups",
  //   iconClass: "icofont-briefcase",
  //   breadcrumbMessage: "",
  //   isCategory: false,
  //   isApp: false,
  //   children: [],
  //   roles: ["Superuser","User", "Manager", "Director"],
  //   departments: [
  //     "Projects",
  //     "HR",
  //     "Marketing",
  //     "Tender",
  //     "Procurement"
  //   ]
  // },

  //Chat
  {
    name: "Chat",
    routerLink: ["/chat"],
    identifier: "Chat",
    iconClass: "icofont-chat",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "HR", "Marketing", "Tender", "Procurement"],
  },
  //Calendar
  {
    name: "Calendar",
    routerLink: ["/calendar"],
    identifier: "Calendar",
    iconClass: "icofont-calendar",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "Manager", "Director"],
    departments: ["HR", "Marketing", "Tender", "Procurement"],
  },
  // *************************************************************

  //Job offer
  {
    name: "Job offer",
    routerLink: ["/"],
    identifier: "Job offer",
    iconClass: "icofont-search-job",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["HR", "Finance"],
  },
  //Add Customer
  {
    name: "Add Customer",
    routerLink: ["/"],
    identifier: "Add Customer",
    iconClass: "icofont-users",
    //<i class="icofont-add-users"></i>
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Procurement", "Finance"],
  },

  //Cost Center
  {
    name: "Cost Center ",
    routerLink: ["/"],
    identifier: "Cost Center ",
    iconClass: "icofont-money",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Procurement", "Projects", "Finance"],
  },

  //Store
  {
    name: "Store ",
    routerLink: ["/"],
    identifier: "Store ",
    iconClass: "icofont-shopify",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Finance"],
  },
  //Project invoice
  {
    name: "Project invoice ",
    routerLink: ["/"],
    identifier: "Project invoice ",
    iconClass: "icofont-file-document",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Finance"],
  },

  //Reports
  {
    name: "Reports",
    routerLink: ["/reports"],
    identifier: "Reports",
    iconClass: "icofont-law-document",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
    roles: ["Superuser", "User", "Manager", "Director"],
    departments: ["Projects", "HR", "Finance", "Marketing", "Tender", "Procurement"],
  },

  //Approval
  {
    name: "Approval",
    routerLink: ["/"],
    identifier: "Approval ",
    iconClass: "icofont-checked",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: true,
    children: [],
    roles: ["Manager"],
    departments: ["Finance"],
  },
];
