import { Company } from "./Company";
import { Customer } from "./Customer";
import { SiteRequest } from "./Site_request";
import { PettyCashRequest } from "./Pc_request";
import { MaterialRequest } from "./Material_request";
import { PurchaseOrderRequest } from "./Po_request";
// import { Group } from './Group';
import { Inventory } from "./Inventory";
import { User } from "./User";
import { Contract } from "./Contract";
import { Invoice } from "./Invoice";
import { Employee } from "./Employee";
import { DailyReport } from "./Daily_report";

export interface Tender {
  id: string;
  code: string | null;
  tender_status: string;
  // status: typeof ENUMS.STATUS;
  user: { id: string; name: string };
  date: string;
  hand_over: string;
  files: string[];
  comments: { id: number; userId: string; name: string; comment: string }[];
  company: Company;
  name: string;
  description: string | null;
  customer_details: { id: string; name: string };
  kpi: number;
  longitude: number | null;
  latitude: number | null;
  thumbnail?: File;
  bid_value: number;
  duration: number | null;

  delivery_date: string;
  contract_date: string;
  contract_number: string | null;
  sites_count: number;
  buildings_count: number;
  floors_count: number;
  total_budget: number;
  po_budget: number;
  po_expenses: number;
  pc_budget: number;
  pc_expenses: number;
  staff_budget: number;
  staff_expenses: number;
  subcontractor_budget: number;
  subcontractor_expenses: number;
  comments_count: number | null;
  members_count: number | null;
  manager: { id: string; name: string };
  daily_report_groups: {
    groupId: string;
    groupName: string;
    employees: string[];
  }[];
  assistants?: { label: string; value: string }[];
  members: any[];
  customer: Customer;
  users: User[];
  managers: User[];
  // group: Group;
  tasks?: any[];
  inventory: Inventory;
  SiteRequests: SiteRequest[];
  PettyCashRequests: PettyCashRequest[];
  MaterialRequests: MaterialRequest[];
  PurchaseOrderRequests: PurchaseOrderRequest[];
  Contracts: Contract[];
  invoices: Invoice[];
  daily_reports: DailyReport[];
  kpi_records: TenderKpi[];
  createdAt: Date;
  updatedAt: Date;
}

export interface SelectedTender {
  id: string;
  name?: string;
  latitude?: number;
  longitude?: number;
  description?: string;
  bid_value?: number;
  total_budget?: number;
  po_budget?: number;
  po_expenses?: number;
  pc_budget?: number;
  pc_expenses?: number;
  staff_budget?: number;
  staff_expenses?: number;
  subcontractor_budget?: number;
  subcontractor_expenses?: number;
  contract_date?: string;
  delivery_date?: string;
  duration?: number;
  customer?: any;
  sites_count?: number;
  buildings_count?: number;
  floors_count?: number;
  contract_number?: string;
  manager?: { id: string; name: string };
  assistants?: { label: string; value: string }[];
  managers?: Employee[];
  customer_details?: { id: string; name: string };
  comments?: Comment[];
  tasks?: any[];
  file?: any;
  files?: File[];
  group?: any;
  attachment_count?: number;
  members_count?: number;
  comments_count?: number;
  tasks_count?: number;
  thumbnail?: any;
  members?: any[];
  tender_status?: string;
  tenderfile_set?: any[];
}
export interface TenderKpi {
  id: string;
  date: string;
  total_kpi: number;
  tender: Tender;
  createdAt: Date;
  updatedAt: Date;
}

export default Tender;
